# ==============================================================================
# DATASOURCE CONFIGURATION (Reactive PostgreSQL)
# ==============================================================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.reactive.url=postgresql://localhost:5432/reviewer_db

# Reactive Connection Pool Tuning
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive.idle-timeout=PT10M

# ==============================================================================
# DATABASE MIGRATIONS (Flyway - Standard JDBC for Schema Control)
# ==============================================================================
# Como estamos usando driver reativo, o Flyway precisa de uma conexão JDBC paralela para rodar as migrations
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/reviewer_db
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# ==============================================================================
# MESSAGING CONFIGURATION (Apache Kafka Ecosystem)
# ==============================================================================
kafka.bootstrap.servers=localhost:9092

# Incoming Channel (Consumidor de Análises)
quarkus.messaging.incoming.analysis-in.connector=smallrye-kafka
quarkus.messaging.incoming.analysis-in.topic=reviewer.analysis.events
quarkus.messaging.incoming.analysis-in.auto.offset.reset=earliest
# Definição do deserializador (Usando String para payload em JSON)
quarkus.messaging.incoming.analysis-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Outgoing Channel (Produtor de Notificações)
quarkus.messaging.outgoing.notifications-out.connector=smallrye-kafka
quarkus.messaging.outgoing.notifications-out.topic=reviewer.notifications.events
# Mude temporariamente esta linha para apontar para o mesmo tópico do incoming:
# quarkus.messaging.outgoing.notifications-out.topic=reviewer.analysis.events
# Definição do serializador (Usando String para enviar o payload em formato JSON)
quarkus.messaging.outgoing.notifications-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# ==============================================================================
# GLOBAL APP CONFIGURATIONS
# ==============================================================================
quarkus.http.port=8080
quarkus.log.level=INFO
quarkus.log.category."br.com.dev_solutions".level=DEBUG